
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Francisco Javier Sánchez De La Torre
 */
public class GUI01 extends javax.swing.JFrame {

    /**
     * Creates new form GUI01
     */
    public GUI01() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /*Boton Limpiar*/
    public void limpiar() {
        tf1.setText("");
        tf2.setText("");
        cCelsius.setSelected(true);
        SeleccionarCelsius();
        combo.setSelectedIndex(1);
        tf1.requestFocus();
    }

    /*Metodos para que cuando se leccione un checkbox se deseleccionen los otros
     y cambie los label de la izquierda*/
    public void SeleccionarCelsius() {
        TitledBorder borde1 = new TitledBorder("Convierte de º Celsius");
        borde1.setTitleJustification(TitledBorder.LEFT);
        borde1.setTitlePosition(TitledBorder.TOP);
        panel1.setBorder(borde1);
        label1.setText("º C");

        cFaren.setSelected(false);
        cKelvin.setSelected(false);
    }

    public void SeleccionarFaren() {
        TitledBorder borde1 = new TitledBorder("Convierte de º Farenheit");
        borde1.setTitleJustification(TitledBorder.LEFT);
        borde1.setTitlePosition(TitledBorder.TOP);
        panel1.setBorder(borde1);
        label1.setText("º F");

        cCelsius.setSelected(false);
        cKelvin.setSelected(false);
    }

    public void SeleccionarKelvin() {
        TitledBorder borde1 = new TitledBorder("Convierte de º Kelvin");
        borde1.setTitleJustification(TitledBorder.LEFT);
        borde1.setTitlePosition(TitledBorder.TOP);
        panel1.setBorder(borde1);
        label1.setText("º K");

        cFaren.setSelected(false);
        cCelsius.setSelected(false);
    }

    /*Metodo para que cuando seleccione un elemento en el combobox se cambien
     los label de la derecha*/
    public void SeleccionarCombo() {
        if (combo.getSelectedIndex() == 0) {
            System.out.println(combo.getSelectedIndex());
            TitledBorder borde2 = new TitledBorder("a º Celsius");
            borde2.setTitleJustification(TitledBorder.LEFT);
            borde2.setTitlePosition(TitledBorder.TOP);
            panel2.setBorder(borde2);
            label2.setText("º C");
        }
        if (combo.getSelectedIndex() == 1) {
            System.out.println(combo.getSelectedIndex());
            TitledBorder borde2 = new TitledBorder("a º Farenheit");
            borde2.setTitleJustification(TitledBorder.LEFT);
            borde2.setTitlePosition(TitledBorder.TOP);
            panel2.setBorder(borde2);
            label2.setText("º F");
        }
        if (combo.getSelectedIndex() == 2) {
            System.out.println(combo.getSelectedIndex());
            TitledBorder borde2 = new TitledBorder("a º Kelvin");
            borde2.setTitleJustification(TitledBorder.LEFT);
            borde2.setTitlePosition(TitledBorder.TOP);
            panel2.setBorder(borde2);
            label2.setText("º k");
        }
    }

    public void realizarCoversion() {
        int aux = Integer.parseInt(tf1.getText());

        if (cCelsius.isSelected() && combo.getSelectedIndex() == 1) {
            double convertido = (aux - (32 * (5 / 9)));
            tf2.setText("" + convertido);
        }
        if (cCelsius.isSelected() && combo.getSelectedIndex() == 2) {
            double convertido = aux - 273.15;
            tf2.setText("" + convertido);
        }
        if (cFaren.isSelected() && combo.getSelectedIndex() == 0) {
            double convertido = ((aux * (9 / 5)) + 32);
            tf2.setText("" + convertido);
        }
        if (cFaren.isSelected() && combo.getSelectedIndex() == 2) {
            double convertido = ((aux * (9 / 5)) - 241.15);
            tf2.setText("" + convertido);
        }
        if (cKelvin.isSelected() && combo.getSelectedIndex() == 0) {
            double convertido = aux + 273.12;
            tf2.setText("" + convertido);
        }
        if (cKelvin.isSelected() && combo.getSelectedIndex() == 1) {
            double convertido = (aux + (241.15 * (5 / 9)));
            tf2.setText("" + convertido);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        cCelsius = new javax.swing.JCheckBox();
        cFaren = new javax.swing.JCheckBox();
        cKelvin = new javax.swing.JCheckBox();
        panel2 = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox();
        realizar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(525, 367));
        getContentPane().setLayout(null);
        getContentPane().add(tf1);
        tf1.setBounds(50, 40, 130, 22);

        tf2.setEditable(false);
        getContentPane().add(tf2);
        tf2.setBounds(270, 40, 130, 22);

        label1.setText("º C");
        getContentPane().add(label1);
        label1.setBounds(200, 40, 50, 20);

        label2.setText("º F");
        getContentPane().add(label2);
        label2.setBounds(430, 40, 40, 20);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Convierte de º Celsius", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panel1.setLayout(null);

        cCelsius.setSelected(true);
        cCelsius.setText("º Celsius");
        cCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCelsiusActionPerformed(evt);
            }
        });
        panel1.add(cCelsius);
        cCelsius.setBounds(30, 20, 79, 25);

        cFaren.setText("º Farenheit");
        cFaren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFarenActionPerformed(evt);
            }
        });
        panel1.add(cFaren);
        cFaren.setBounds(30, 50, 93, 25);

        cKelvin.setText("º Kelvin");
        cKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKelvinActionPerformed(evt);
            }
        });
        panel1.add(cKelvin);
        cKelvin.setBounds(30, 80, 71, 25);

        getContentPane().add(panel1);
        panel1.setBounds(30, 110, 200, 160);

        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "a º Farenheit", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panel2.setLayout(null);

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "º Celsius", "º Farenheit", "º Kelvin" }));
        combo.setSelectedIndex(1);
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        panel2.add(combo);
        combo.setBounds(20, 20, 150, 22);

        getContentPane().add(panel2);
        panel2.setBounds(260, 110, 200, 160);

        realizar.setText("Realizar");
        realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarActionPerformed(evt);
            }
        });
        getContentPane().add(realizar);
        realizar.setBounds(30, 290, 110, 25);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar);
        limpiar.setBounds(200, 290, 79, 25);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(350, 290, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    private void cCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCelsiusActionPerformed
        SeleccionarCelsius();
    }//GEN-LAST:event_cCelsiusActionPerformed

    private void cFarenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFarenActionPerformed
        SeleccionarFaren();
    }//GEN-LAST:event_cFarenActionPerformed

    private void cKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKelvinActionPerformed
        SeleccionarKelvin();
    }//GEN-LAST:event_cKelvinActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        SeleccionarCombo();
    }//GEN-LAST:event_comboActionPerformed

    private void realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarActionPerformed
        try {
            realizarCoversion();
        } catch (Exception e) {
            if (tf1.getText() == "") {
                JOptionPane.showMessageDialog(null, "No ha introducido nada.", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Ha introducido un campo erroneo o no válido.", "Error", JOptionPane.WARNING_MESSAGE);
            }
            tf1.setText(null);
        }
    }//GEN-LAST:event_realizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cCelsius;
    private javax.swing.JCheckBox cFaren;
    private javax.swing.JCheckBox cKelvin;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton limpiar;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JButton realizar;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
