
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fran De La Torre
 */
public class GUI extends javax.swing.JFrame {

    ArrayList<String> Palabras;
    ArrayList<String> listaGuiones;
    ArrayList<String> listaLetras;
    String palabraSeleccionada;
    String stringGuion;
    String estaSi;
    Boolean comprobador;
    int nIntentos = 5;

    public GUI() {
        initComponents();
        Palabras = new ArrayList<String>();
        listaGuiones = new ArrayList<String>();
        listaLetras = new ArrayList<String>();
    }

    public void addPalabras() {
        String nuevaPalabra = tAdd.getText();
        if (!nuevaPalabra.equals("")) {
            Palabras.add(nuevaPalabra);
            tAdd.setText("");
            tAdd.requestFocus();
            System.out.println(Palabras);
        } else {
            System.err.println("Introduce una palabra.");
        }
    }

    public void jugar() {
        try {
            nIntentos = 5;
            stringGuion = "";
            tPalabra.setText("");
            listaLetras.clear();
            listaGuiones.clear();

            int longitud = Palabras.size();
            int palabreja = (int) (Math.random() * longitud);
            palabraSeleccionada = Palabras.get(palabreja);
            Palabras.remove(palabreja);
            System.out.println(palabraSeleccionada);

            for (int i = 0; i < palabraSeleccionada.length(); i++) {
                listaLetras.add(palabraSeleccionada.charAt(i) + "");
                listaGuiones.add(i, "_");
            }
            for (int i = 0; i < listaGuiones.size(); i++) {
                stringGuion += "_";
            }
            tPalabra.setText(stringGuion);
            tIntentos.setText(nIntentos + "");
        } catch (Exception evt) {
            System.err.println("No hay ninguna palabra introducida para jugar.");
        }
    }

    public void jugando() {
        comprobador = false;
        estaSi = "";
        String letra = tLetra.getText();
        tLetra.setText("");
        for (int i = 0; i < listaLetras.size(); i++) {
            if (listaLetras.get(i).equals(letra)) {
                listaGuiones.set(i, letra);
                comprobador = true;
            }
        }
        for (int i = 0; i < listaGuiones.size(); i++) {
            estaSi += listaGuiones.get(i);
        }
        if (estaSi.equals(palabraSeleccionada)) {
            dialogo3.setVisible(true);
        }

        if (!comprobador) {
            nIntentos--;
            tIntentos.setText(nIntentos + "");
            comprobador = false;
        }
        if (nIntentos == 0) {
            dialogo2.setVisible(true);
        }

        tPalabra.setText(estaSi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tAdd = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        dialogo2 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        cJugando = new javax.swing.JButton();
        dSalir = new javax.swing.JButton();
        dialogo3 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tPalabra = new javax.swing.JTextField();
        tIntentos = new javax.swing.JTextField();
        tLetra = new javax.swing.JTextField();
        introducir = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();

        dialogo.setMinimumSize(new java.awt.Dimension(500, 200));

        jLabel4.setText("Palabra");

        add.setText("Añadir");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoLayout = new javax.swing.GroupLayout(dialogo.getContentPane());
        dialogo.getContentPane().setLayout(dialogoLayout);
        dialogoLayout.setHorizontalGroup(
            dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoLayout.createSequentialGroup()
                        .addComponent(tAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(dialogoLayout.createSequentialGroup()
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir)
                        .addGap(107, 107, 107))))
        );
        dialogoLayout.setVerticalGroup(
            dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(salir))
                .addGap(23, 23, 23))
        );

        dialogo2.setMinimumSize(new java.awt.Dimension(570, 170));
        dialogo2.setPreferredSize(new java.awt.Dimension(560, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("¡Has perdido! ¿Qué deseas hacer?");

        cJugando.setText("Continuar Jugando");
        cJugando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJugandoActionPerformed(evt);
            }
        });

        dSalir.setText("Salir");
        dSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogo2Layout = new javax.swing.GroupLayout(dialogo2.getContentPane());
        dialogo2.getContentPane().setLayout(dialogo2Layout);
        dialogo2Layout.setHorizontalGroup(
            dialogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(dialogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogo2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(dialogo2Layout.createSequentialGroup()
                        .addComponent(cJugando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dSalir)
                        .addGap(90, 90, 90))))
        );
        dialogo2Layout.setVerticalGroup(
            dialogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addGroup(dialogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cJugando)
                    .addComponent(dSalir))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        dialogo3.setPreferredSize(new java.awt.Dimension(580, 170));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("¡HAS ACERTADO!");

        jButton1.setText("Seguir Jugando");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogo3Layout = new javax.swing.GroupLayout(dialogo3.getContentPane());
        dialogo3.getContentPane().setLayout(dialogo3Layout);
        dialogo3Layout.setHorizontalGroup(
            dialogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogo3Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(185, 185, 185))
            .addGroup(dialogo3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(117, 117, 117))
        );
        dialogo3Layout.setVerticalGroup(
            dialogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(40, 40, 40)
                .addGroup(dialogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Palabra");

        jLabel2.setText("Letra");

        jLabel3.setText("Intentos");

        tPalabra.setEditable(false);

        tIntentos.setEditable(false);

        tLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tLetraKeyReleased(evt);
            }
        });

        introducir.setText("Introducir Palabras");
        introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirActionPerformed(evt);
            }
        });

        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(introducir)
                        .addGap(27, 27, 27)
                        .addComponent(jugar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tIntentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introducir)
                    .addComponent(finalizar)
                    .addComponent(jugar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirActionPerformed
        dialogo.setVisible(true);
    }//GEN-LAST:event_introducirActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        addPalabras();
    }//GEN-LAST:event_addActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dialogo.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        jugar();
    }//GEN-LAST:event_jugarActionPerformed

    private void tLetraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tLetraKeyReleased
        jugando();
    }//GEN-LAST:event_tLetraKeyReleased

    private void cJugandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJugandoActionPerformed
        jugar();
        dialogo2.setVisible(false);
    }//GEN-LAST:event_cJugandoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jugar();
        dialogo3.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_dSalirActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_finalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cJugando;
    private javax.swing.JButton dSalir;
    private javax.swing.JDialog dialogo;
    private javax.swing.JDialog dialogo2;
    private javax.swing.JDialog dialogo3;
    private javax.swing.JButton finalizar;
    private javax.swing.JButton introducir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jugar;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tAdd;
    private javax.swing.JTextField tIntentos;
    private javax.swing.JTextField tLetra;
    private javax.swing.JTextField tPalabra;
    // End of variables declaration//GEN-END:variables
}
